[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

# Matikan post-processing biar deploy tidak macet
[build.processing]
  skip_processing = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

